### ISSUE TITLE
购物车最下边商品被遮挡

### ISSUE THREAD

**Issue by Gullrye** [newbee-ltd/newbee-mall-vue-app#41]
你好，购物车里商品较多时，会把最下边的商品遮挡住。有空可以处理下。

**Comment by ZHENFENG13** [comment]
好的

**Comment by Gullrye** [comment]
口红、耳机等 **详情页上的商品图片链接无效**。
比如耳机的详情页图片：
```
正确链接 http://backend-api-01.newbee.ltd/goods-img/0dc503b2-90a2-4971-9723-c085a1844b76.jpg
无效链接           http://localhost:28089/goods-img/0dc503b2-90a2-4971-9723-c085a1844b76.jpg
```

**Comment by Gullrye** [comment]
> 你好，购物车里商品较多时，会把最下边的商品遮挡住。有空可以处理下。

好像是 chrome 和 edge 显示的问题，firefox 和手机上看着没毛病。

**Comment by ZHENFENG13** [comment]
> 口红、耳机等 **详情页上的商品图片链接无效**。 比如耳机的详情页图片：
> 
> ```
> 正确链接 http://backend-api-01.newbee.ltd/goods-img/0dc503b2-90a2-4971-9723-c085a1844b76.jpg
> 无效链接           http://localhost:28089/goods-img/0dc503b2-90a2-4971-9723-c085a1844b76.jpg
> ```

好的，这些错误链接我改一下

**Comment by ZHENFENG13** [comment]
> 口红、耳机等 **详情页上的商品图片链接无效**。 比如耳机的详情页图片：
> 
> ```
> 正确链接 http://backend-api-01.newbee.ltd/goods-img/0dc503b2-90a2-4971-9723-c085a1844b76.jpg
> 无效链接           http://localhost:28089/goods-img/0dc503b2-90a2-4971-9723-c085a1844b76.jpg
> ```

有截图吗？我没看到错误图片，是哪个项目里出现的？

**Comment by Gullrye** [comment]
比如首页最底下的T恤，点进去会发现商品详情图片错了。
![image](https://user-images.githubusercontent.com/46998709/136164206-8241df44-879f-41da-93e9-3eaa6a46c81e.png)

**Comment by ZHENFENG13** [comment]
> 比如首页最底下的T恤，点进去会发现商品详情图片错了。 ![image](https://user-images.githubusercontent.com/46998709/136164206-8241df44-879f-41da-93e9-3eaa6a46c81e.png)

已处理。
